import React, { useState, useEffect } from 'react'
import ProductModal from './ProductModal'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'

export default function ProductDetails() {
  const { user } = useAuth()
  
  // State for products from Supabase
  const [products, setProducts] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  
  const [selectedProduct, setSelectedProduct] = useState(null)
  const [isModalOpen, setIsModalOpen] = useState(false)

  // Fetch products from Supabase
  const fetchProducts = async () => {
    if (!user) return
    
    try {
      setLoading(true)
      setError(null)
      
      const { data, error: fetchError } = await supabase
        .from('products')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })

      if (fetchError) throw fetchError

      // Transform data to match component's expected format
      const transformedProducts = data?.map(product => ({
        id: product.id,
        productId: product.id, // Keep UUID for editing
        name: product.name || '',
        price: product.price ? `₹${product.price}` : '₹0',
        priceValue: product.price || 0,
        imageSrc: product.image_src || product.image_url || 'https://via.placeholder.com/400',
        imageAlt: product.image_alt || product.name || 'Product image',
        description: product.description || '',
        category: product.category || '',
        quantity: product.quantity || 0,
        sku: product.sku || '',
        status: product.status || 'Active',
        totalSold: product.total_sold || 0,
        tags: product.tags || [],
        created_at: product.created_at,
        updated_at: product.updated_at
      })) || []

      setProducts(transformedProducts)
    } catch (err) {
      console.error('Error fetching products:', err.message)
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  // Fetch products when user changes
  useEffect(() => {
    if (user) {
      fetchProducts()
    }
  }, [user])

  // Set up real-time subscription for products
  useEffect(() => {
    if (!user) return

    const productsChannel = supabase
      .channel('products-changes')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'products',
          filter: `user_id=eq.${user.id}`
        },
        (payload) => {
          console.log('Product change detected:', payload)
          fetchProducts() // Refresh products on any change
        }
      )
      .subscribe()

    return () => {
      supabase.removeChannel(productsChannel)
    }
  }, [user])

  // Open modal with product data
  const handleProductClick = (product) => {
    setSelectedProduct(product)
    setIsModalOpen(true)
  }

  // Handle adding new product
  const handleAddProduct = () => {
    const newProduct = {
      id: null, // Will be set by Supabase
      productId: null,
      name: 'New Product',
      price: '₹0',
      priceValue: 0,
      imageSrc: 'https://via.placeholder.com/400',
      imageAlt: 'New product image',
      description: 'Add product description here',
      category: '',
      quantity: 0,
      sku: '', // Will be auto-generated by Supabase
      status: 'Active',
      totalSold: 0,
      tags: [],
      isNew: true
    }
    setSelectedProduct(newProduct)
    setIsModalOpen(true)
  }

  // Handle product save (insert or update in Supabase)
  const handleSave = async (productData) => {
    if (!user) return

    try {
      // Remove UI-specific fields (keep price in supabaseData)
      const { productId, isNew, priceValue, ...supabaseData } = productData
      
      // Format data for Supabase
      const supabaseProductData = {
        user_id: user.id,
        name: supabaseData.name,
        price: parseFloat(supabaseData.price?.replace(/[₹$]/g, '') || 0),
        description: supabaseData.description || '',
        category: supabaseData.category || 'Other',
        quantity: parseInt(supabaseData.quantity) || 0,
        sku: supabaseData.sku || null, // Will be auto-generated if null
        status: supabaseData.status || 'Active',
        image_src: supabaseData.imageSrc || null,
        image_alt: supabaseData.imageAlt || null,
        image_url: supabaseData.imageSrc || null,
        tags: supabaseData.tags || []
      }

      if (productData.isNew) {
        // Insert new product
        const { data, error: insertError } = await supabase
          .from('products')
          .insert([supabaseProductData])
          .select()

        if (insertError) throw insertError
        
        // The real-time subscription will automatically update the list
        console.log('Product created successfully:', data)
      } else {
        // Update existing product
        const { error: updateError } = await supabase
          .from('products')
          .update(supabaseProductData)
          .eq('id', productData.productId)
          .eq('user_id', user.id)

        if (updateError) throw updateError
        
        // The real-time subscription will automatically update the list
        console.log('Product updated successfully')
      }
      
      // Close modal - real-time subscription will update the list
      setIsModalOpen(false)
      setSelectedProduct(null)
    } catch (err) {
      console.error('Error saving product:', err.message)
      alert('Failed to save product: ' + err.message)
    }
  }

  // Handle delete product
  const handleDeleteProduct = async (productId) => {
    if (!user) return
    
    const confirmDelete = window.confirm('Are you sure you want to delete this product?')
    if (!confirmDelete) return

    try {
      const { error: deleteError } = await supabase
        .from('products')
        .delete()
        .eq('id', productId)
        .eq('user_id', user.id)

      if (deleteError) throw deleteError
      
      // The real-time subscription will automatically update the list
      console.log('Product deleted successfully')
      setIsModalOpen(false)
      setSelectedProduct(null)
    } catch (err) {
      console.error('Error deleting product:', err.message)
      alert('Failed to delete product: ' + err.message)
    }
  }

  // Get status badge color
  const getStatusBadge = (status) => {
    switch (status) {
      case 'Active':
        return 'bg-emerald-500/10 text-emerald-400'
      case 'Inactive':
        return 'bg-gray-500/10 text-gray-400'
      case 'Discontinued':
        return 'bg-red-500/10 text-red-400'
      default:
        return 'bg-gray-500/10 text-gray-400'
    }
  }

  // Format price for display
  const formatPrice = (priceStr) => {
    if (!priceStr) return '₹0'
    return priceStr
  }

  return (
    <div className="bg-[#0A0A0A]">
      <div className="p-6">
        {/* Header */}
        <h1 className="text-2xl font-bold mb-6 text-white bg-gradient-to-r from-white to-[#748298] bg-clip-text text-transparent">
          Products Catalog
        </h1>
        <div className="flex items-center justify-between mb-6">
          <div>
            <p className="text-sm text-slate-400 mt-1">
              {products.length} products in your catalog
            </p>
          </div>
          <button
            onClick={handleAddProduct}
            className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-colors flex items-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4" />
            </svg>
            Add Product
          </button>
        </div>

        {/* Loading State */}
        {loading && (
          <div className="text-center py-12">
            <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-500"></div>
            <p className="mt-4 text-slate-400">Loading products...</p>
          </div>
        )}

        {/* Error State */}
        {error && !loading && (
          <div className="text-center py-12">
            <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-red-500/10 mb-4">
              <svg className="w-6 h-6 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <p className="text-lg text-red-400">Error loading products</p>
            <p className="text-sm text-slate-400 mt-1">{error}</p>
          </div>
        )}

        {/* Products Grid */}
        {!loading && !error && (
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {products.map((product) => (
              <div
                key={product.id}
                onClick={() => handleProductClick(product)}
                className="group bg-[#0A0A0A] border border-gray-800 rounded-xl overflow-hidden hover:border-gray-700 hover:bg-gray-900 transition-all duration-300 cursor-pointer"
              >
                <div className="relative aspect-square overflow-hidden">
                  <img
                    alt={product.imageAlt}
                    src={product.imageSrc}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                    onError={(e) => {
                      e.target.src = 'https://via.placeholder.com/400'
                    }}
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                  
                  {/* Status badge */}
                  <div className="absolute top-3 right-3">
                    <span className={`inline-flex items-center px-2 py-1 rounded-md text-xs font-medium ${getStatusBadge(product.status)}`}>
                      {product.status}
                    </span>
                  </div>
                </div>
                
                <div className="p-4">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <h3 className="text-sm font-medium text-white group-hover:text-indigo-400 transition-colors">
                        {product.name}
                      </h3>
                      <p className="text-xs text-slate-500 mt-1">{product.category}</p>
                    </div>
                    <p className="text-lg font-semibold text-white ml-2">{formatPrice(product.price)}</p>
                  </div>
                  
                  {/* Quick stats */}
                  <div className="flex items-center gap-4 mt-3 pt-3 border-t border-gray-800">
                    <div className="flex items-center text-xs text-slate-400">
                      <svg className="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
                      </svg>
                      {product.quantity} in stock
                    </div>
                    <div className="flex items-center text-xs text-slate-400">
                      <svg className="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                      </svg>
                      {product.sku}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Empty state if no products */}
        {!loading && !error && products.length === 0 && (
          <div className="text-center py-12">
            <svg className="mx-auto h-12 w-12 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
            </svg>
            <h3 className="mt-2 text-sm font-medium text-white">No products</h3>
            <p className="mt-1 text-sm text-slate-400">Get started by adding a new product.</p>
            <div className="mt-6">
              <button
                onClick={handleAddProduct}
                className="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-colors"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4" />
                </svg>
                Add Product
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Product Modal */}
      <ProductModal
        isOpen={isModalOpen}
        onClose={() => {
          setIsModalOpen(false)
          setSelectedProduct(null)
        }}
        product={selectedProduct}
        onSave={handleSave}
        onDelete={handleDeleteProduct}
        user={user}
      />
    </div>
  )
}

